


services:
  django:
    build:
      context: .
    container_name: django_app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_worker
    ports:
    - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A tutoring_api worker --loglevel=info
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data: